<?php

use Illuminate\Database\Seeder;

class TeachersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('teachers')->delete();
        
        \DB::table('teachers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '陈红霞',
                'email' => 'test@sudo.team',
                'password' => '$2y$10$9ZMTG1WavDPnCZ9VTmnllevZyrlSwUGcYO/Uhe.Al6dvEcSbYLcO.',
                'remember_token' => NULL,
                'description' => 'Doloremque illo repellendus at eos quis nostrum. Enim sunt cupiditate amet in earum aut. Aperiam necessitatibus magni laborum quo.',
                'video' => NULL,
                'teaching_since' => NULL,
                'unit_price' => 99.0,
                'enabled' => 0,
                'created_at' => NULL,
                'updated_at' => '2016-08-05 10:57:20',
                'deleted_at' => '2016-08-05 10:57:20',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => '关欣',
                'email' => 'totam33@example.org',
                'password' => '$2y$10$P7V9166QcMlKgqXREx5yBOMml9pf/DruRv/oxrXknrVRe8poo0AGi',
                'remember_token' => 'pVLcpfpid8',
                'description' => 'Quibusdam corrupti veritatis voluptatum quia esse. Id esse dolores recusandae officiis velit eligendi nihil. Veniam sit eum maxime numquam.',
                'video' => NULL,
                'teaching_since' => '2016-08-05 20:14:00',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 10:57:31',
                'deleted_at' => '2016-08-05 10:57:31',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => '万智敏',
                'email' => 'scum@example.com',
                'password' => '$2y$10$krnb/q6rNuGhtimPvuwg3.L52L3jgjn4SnPTIoaws.UWRpgBoL7Ca',
                'remember_token' => 'KezA3CiY8g',
                'description' => 'Minus quia optio quas blanditiis ratione libero. Ut mollitia ducimus omnis reiciendis autem numquam ut nisi.',
                'video' => NULL,
                'teaching_since' => '1979-08-05 09:08:26',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 10:57:53',
                'deleted_at' => '2016-08-05 10:57:53',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '龚智明',
                'email' => 'qui43@example.org',
                'password' => '$2y$10$RdyoG//JEL.bIB57WS2MUuUus1aQ16rwJkPtB4CF6y854tW3WTX4e',
                'remember_token' => 'XuRiOPh8GI',
                'description' => 'Et at iste explicabo quo sunt et. Voluptatem dolores dignissimos beatae. Alias rerum dolores quia quia eveniet consequatur nemo.',
                'video' => NULL,
                'teaching_since' => '1979-08-05 09:08:26',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 10:58:09',
                'deleted_at' => '2016-08-05 10:58:09',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => '纪浩',
                'email' => 'aest@example.com',
                'password' => '$2y$10$WEw0EcjPw4iRCoc47l1UcOa3F7kyUjk20dgJWU.Yu5z.eSovwhNfa',
                'remember_token' => 'iVAtLBbbMr',
                'description' => 'Corrupti excepturi voluptates nesciunt quis vel. Aut perspiciatis ipsum qui error. Aut aut tenetur sequi incidunt quod.',
                'video' => NULL,
                'teaching_since' => '2016-08-05 20:09:00',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 10:58:16',
                'deleted_at' => '2016-08-05 10:58:16',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => '巫玉华',
                'email' => 'deserunt.neque@example.net',
                'password' => '$2y$10$bWxHN6YvJWr5ZwSHA86uFu1qOcDKkmriGODijd5Z1jaPQYrrxFll.',
                'remember_token' => 'tnBUtHKCmW',
                'description' => 'Fuga provident rem et debitis distinctio voluptatem at iure. Animi est voluptate magni expedita. Harum quia debitis corrupti autem. Sequi consequatur a in voluptates consequatur tempore.',
                'video' => NULL,
                'teaching_since' => '1984-08-05 09:08:26',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 10:58:23',
                'deleted_at' => '2016-08-05 10:58:23',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => '齐桂兰',
                'email' => 'sed.voluptatem@example.com',
                'password' => '$2y$10$xRlOD2jaaI4FiuNuaTtY/.jsxvVsyv4rGhPqd8dcg1temOPeJubFa',
                'remember_token' => 'TR1TJtsEAU',
                'description' => 'Quod laborum aut qui voluptates voluptas consequatur recusandae suscipit. Eos sunt suscipit sed dolorem corporis est error. Autem sed explicabo distinctio rerum. Autem veniam maiores qui quam.',
                'video' => NULL,
                'teaching_since' => '1991-08-05 09:08:26',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 10:58:32',
                'deleted_at' => '2016-08-05 10:58:32',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => '岳嘉俊',
                'email' => 'psuscipit@example.net',
                'password' => '$2y$10$Ow1iv3ylVRNRsPMb1Tjql.VEEVYenty.brFCGcarjY48yAezhKPuS',
                'remember_token' => 'M387Bqiiwr',
                'description' => 'Quidem quibusdam consequuntur culpa minima ex quis placeat. Tempore enim amet doloribus corporis facere modi nesciunt iure. Illum et cum est eum animi non voluptas. Ut et praesentium sequi et.',
                'video' => NULL,
                'teaching_since' => '1987-08-05 09:08:26',
                'unit_price' => 99.0,
                'enabled' => 0,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 10:59:38',
                'deleted_at' => '2016-08-05 10:59:38',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => '衣琳',
                'email' => 'et.et@example.org',
                'password' => '$2y$10$sBNqWCY.Jv0e3czAOzqYtuNi0S47WTX8.UjhGDqVk2wyvQYtbG88u',
                'remember_token' => 'tnJzHrgoqu',
                'description' => 'Quisquam iusto odit non. Molestiae est molestiae perspiciatis harum quibusdam amet. Cumque quis amet quis veritatis esse maxime. Quidem voluptas quae quam dolorem ipsum.',
                'video' => NULL,
                'teaching_since' => '2016-08-05 20:02:00',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:00:30',
                'deleted_at' => '2016-08-05 11:00:30',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => '倪兵',
                'email' => 'munde@example.com',
                'password' => '$2y$10$j7p7L/yfsO1IgCRVt4VVMeWJmAmvS/RgUq5xSVODmSVXAefZP9NdW',
                'remember_token' => 'svjeHWxM1m',
                'description' => 'Perferendis sunt error itaque. Non quis porro fugiat. Esse maiores id praesentium maxime veritatis. Autem est optio et maxime voluptas ut aliquam quaerat.',
                'video' => NULL,
                'teaching_since' => '1995-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:00:40',
                'deleted_at' => '2016-08-05 11:00:40',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => '曹丽华',
                'email' => 'aperiam_nobis@example.net',
                'password' => '$2y$10$SSoLiC8ryjIWn6FcUeFhOupPZsxwuGYdis6tuU5tQ6MgoYzz57pYm',
                'remember_token' => 'spaEUzAb5R',
                'description' => 'Deserunt sint sint accusamus minus eum. Facere commodi optio non eligendi in. Qui quia enim et nostrum.',
                'video' => NULL,
                'teaching_since' => '1996-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:03:25',
                'deleted_at' => '2016-08-05 11:03:25',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => '庞萍',
                'email' => 'hic71@example.net',
                'password' => '$2y$10$uxt42iXmfVa/FXFXnlIKXeYqm0x6kZq0YtY7.D9kUaqbUKg4yushm',
                'remember_token' => 'vKRG1w1XbW',
                'description' => 'Voluptas et quidem non est tempora eaque expedita autem. Tempora doloremque quod deserunt quisquam. Dolorum perferendis eum recusandae asperiores.',
                'video' => NULL,
                'teaching_since' => '1979-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:03:32',
                'deleted_at' => '2016-08-05 11:03:32',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => '单建明',
                'email' => 'delectus03@example.org',
                'password' => '$2y$10$EjcVuFl5e.hiT04iDfSB9.7POhCJKW36F1jRJjYHiCxv7H.WEJ01.',
                'remember_token' => 'n9ZserDUQq',
                'description' => 'Beatae et nam eos labore. Recusandae et totam eos quas. Molestiae aut quia sed totam eos. Quidem quos facilis placeat.',
                'video' => NULL,
                'teaching_since' => '1976-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 0,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:03:38',
                'deleted_at' => '2016-08-05 11:03:38',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => '徐俊',
                'email' => 'aut56@example.net',
                'password' => '$2y$10$0xOXhDRgQkb4SvdyQYTBg.BeUouz0cqAoCEAooT.YmiwscLn3jcSm',
                'remember_token' => 'wQbffHXwxX',
                'description' => 'Sequi magnam assumenda nihil enim voluptatem. Doloribus nam eius sint illum ea impedit. Natus similique qui earum officiis illum.',
                'video' => NULL,
                'teaching_since' => '1971-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:03:45',
                'deleted_at' => '2016-08-05 11:03:45',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => '关文君',
                'email' => 'placeat60@example.com',
                'password' => '$2y$10$U/cx7YKHUifHigDuUU30J.4/JAE7rtJfvR9.BpSGLdFVi9cnkzrNq',
                'remember_token' => 'gnOsPS4NPW',
                'description' => 'Velit ab odit ut tempore et. Ea eveniet a sapiente unde qui veniam voluptatem. Recusandae ut aut porro ut.',
                'video' => NULL,
                'teaching_since' => '1973-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 0,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:03:52',
                'deleted_at' => '2016-08-05 11:03:52',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => '尹娜',
                'email' => 'aut_placeat@example.org',
                'password' => '$2y$10$m/y55.7Bh.h6PKj6xVlwRO8x8iMVf7QO9bRJaFSyhKVGQJBBLhVd6',
                'remember_token' => 'QLnXcsQ8Iw',
                'description' => 'Dolorem repudiandae similique non corrupti similique voluptas molestias deleniti. Officiis dolorum laudantium voluptas impedit qui. Et maxime deleniti numquam quisquam et alias nobis.',
                'video' => NULL,
                'teaching_since' => '1986-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:04:57',
                'deleted_at' => '2016-08-05 11:04:57',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => '符欢',
                'email' => 'est09@example.org',
                'password' => '$2y$10$Mav4HWS.hrPDKGKI6QwMK.X1KBIWNbJgxc9C57Im9G/fOQqVi3xeW',
                'remember_token' => 'BWx4ewC0Be',
                'description' => 'Quia ipsa eius consequatur quo similique. Doloremque eos molestiae ab in. Neque sint optio aliquam dolorem atque explicabo.',
                'video' => NULL,
                'teaching_since' => '1988-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:05:04',
                'deleted_at' => '2016-08-05 11:05:04',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => '卫楼',
                'email' => 'id_consequatur@example.net',
                'password' => '$2y$10$5eYGLY7viWO3N0mei4UcQuI5C8YjZWfkgxb0oP0BRR.fq8NoRXHZu',
                'remember_token' => 'bvAG6rQoNl',
                'description' => 'Sed libero corporis quia qui sint aspernatur. Voluptas iste autem tempora quis. Tenetur est voluptas ratione possimus.',
                'video' => NULL,
                'teaching_since' => '1981-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:05:28',
                'deleted_at' => '2016-08-05 11:05:28',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => '袁成',
                'email' => 'velit_libero@example.com',
                'password' => '$2y$10$95PGJ85GufLbgH.AvrgJWurF88PIO.vp7U8Wy2ExjjCJ0bzcIXELO',
                'remember_token' => '3yY1im85fW',
                'description' => 'Fuga et et et. Magni dicta nisi voluptatem.',
                'video' => NULL,
                'teaching_since' => '1982-08-05 09:08:27',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:18:28',
                'deleted_at' => '2016-08-05 11:18:28',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => '王博涛',
                'email' => 'krerum@example.org',
                'password' => '$2y$10$PW0baebY2s4nC11s8RZysudmC3nThKw3dVj4LAtlqU3JkmUcA8tAO',
                'remember_token' => 'mWaBWP4oSU',
                'description' => 'Sint eius ratione vitae debitis ut nesciunt tempora. Consequatur facere id voluptatem amet velit. Nesciunt reprehenderit voluptates magnam aut aut deserunt odit.',
                'video' => NULL,
                'teaching_since' => '2016-08-05 20:10:00',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:18:36',
                'deleted_at' => '2016-08-05 11:18:36',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => '车莹',
                'email' => 'molestias95@example.net',
                'password' => '$2y$10$qfomB/6gFBejDd7E5cmUYuga4yeX2rweIzl7oforY7syGN8eq9kiG',
                'remember_token' => 'Wo0Z3uSuL1',
                'description' => 'Fugiat et qui quia magni sit provident. Eos rem id ut tenetur. Vel enim velit autem facere. Molestias dolores exercitationem voluptate eos.',
                'video' => NULL,
                'teaching_since' => '2016-08-05 20:07:00',
                'unit_price' => 99.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 09:08:28',
                'updated_at' => '2016-08-05 11:18:43',
                'deleted_at' => '2016-08-05 11:18:43',
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => '付婷',
                'email' => 'futing@163.com',
                'password' => '',
                'remember_token' => NULL,
                'description' => '',
                'video' => NULL,
                'teaching_since' => '2004-11-30 00:00:00',
                'unit_price' => 39.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 10:26:33',
                'updated_at' => '2016-09-19 11:19:06',
                'deleted_at' => NULL,
                'avatar_file_name' => 'smile.jpg',
                'avatar_file_size' => 336951,
                'avatar_content_type' => 'image/jpeg',
                'avatar_updated_at' => '2016-08-05 10:47:11',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => '侯雪莹',
                'email' => 'houxueying@163.com',
                'password' => '',
                'remember_token' => NULL,
                'description' => '汉语国际教育专业，并拥有汉语国际教育教师资格证，雅思9分。
六年青少英语教学经验，精通多个版本的公立学校教材，对于内容重点的把握精准。
擅长听说和阅读专项提高，采用双语教学法，营造真实语言环境。自建阅读体系和方法，注重解题技巧的培养，用独特的方法让学生轻松理解文章含义，建立英语思维，进而获得自主学习能力。
授课方式灵活多样，善于用语言打动学生，根据学生不同的情况，因材施教，确保每一个学生都可以收获更多。
',
                'video' => NULL,
                'teaching_since' => '2009-11-30 00:00:00',
                'unit_price' => 39.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 10:46:37',
                'updated_at' => '2016-08-05 11:13:32',
                'deleted_at' => NULL,
                'avatar_file_name' => '84782244686673904.jpg',
                'avatar_file_size' => 41587,
                'avatar_content_type' => 'image/jpeg',
                'avatar_updated_at' => '2016-08-05 11:09:55',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => '许萌',
                'email' => 'xumeng@163.com',
                'password' => '',
                'remember_token' => NULL,
                'description' => '毕业于北京林业大学，六年英语教学经验，教授新概念，KET，PET和语法系统。
精通词汇、语法和听说，采用三位一体的教学模式，实现英语能力的全面提升，告别不敢说、怕说错的胆怯心理，向学生诠释“说英语，真的很简单”。讲语法的难点和重点融入到听说中，通过“学以致用”的方式，达到熟练。
课堂氛围活泼，趣味横生，每一个知识点都加入幽默元素，以达到充分理解，轻松记忆，最终实现快乐学习。许老师的人生格言是“快乐学习，学习才能更快乐”。
',
                'video' => NULL,
                'teaching_since' => '2009-11-30 00:00:00',
                'unit_price' => 49.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 10:57:09',
                'updated_at' => '2016-08-05 11:14:21',
                'deleted_at' => NULL,
                'avatar_file_name' => 'lin.jpg',
                'avatar_file_size' => 330523,
                'avatar_content_type' => 'image/jpeg',
                'avatar_updated_at' => '2016-08-05 11:14:16',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => '王密',
                'email' => 'wangmi@163.com',
                'password' => '',
                'remember_token' => NULL,
                'description' => '毕业于湖北民族学院，五年英语教学经验，精通自然拼读、三一口语、新概念和语法等。
王老师喜欢双语教学模式，更容易给学生营造语言环境，边听边说，轻松建立英语思维。自然拼读加三一口语，是王老师的金牌组合课程，全面强化英语听说能力。语法精讲精练课程，帮助零基础学生以最少的时间掌握最多的内容，实现高效学习。对于提高班学生，强化课本考点和重点，传授语法技巧，在考试中处于不败之地。
激情教学风格，用轻松幽默的方式传递英语之美。慷慨激昂的演说，无时不刻为同学们提供正能量。
',
                'video' => NULL,
                'teaching_since' => '2010-11-30 00:00:00',
                'unit_price' => 45.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 11:01:18',
                'updated_at' => '2016-08-05 11:18:47',
                'deleted_at' => NULL,
                'avatar_file_name' => 'abby.jpg',
                'avatar_file_size' => 418425,
                'avatar_content_type' => 'image/jpeg',
                'avatar_updated_at' => '2016-08-05 11:01:40',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => '奚泉',
                'email' => 'xiquan@163.com',
                'password' => '',
                'remember_token' => NULL,
                'description' => '毕业于辽宁对外经贸学院，五年英语教学经验，主讲三一口语、自然拼读和剑桥英语等。
发音标准，擅长口语、听力和语法教学。听是输入，说是输出，二者相结合使学生敢于开口说英语，将考点和技巧融入其中，实现学以致用。语法学习的核心是理解，非机械记忆，奚老师传递理解至上的理念，知其然知其所以然，所教学生考试成绩提高迅速。
幽默型授课风格，极富有感染力的语言，激发学生学习英语的兴趣。推崇兴趣教学法，建立兴趣是成功一半，提高学生的自学能力。
',
                'video' => NULL,
                'teaching_since' => '2010-11-30 00:00:00',
                'unit_price' => 40.0,
                'enabled' => 1,
                'created_at' => '2016-08-05 11:02:23',
                'updated_at' => '2016-08-05 11:18:51',
                'deleted_at' => NULL,
                'avatar_file_name' => 'lexy.jpg',
                'avatar_file_size' => 421113,
                'avatar_content_type' => 'image/jpeg',
                'avatar_updated_at' => '2016-08-05 11:03:10',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => '测试老师',
                'email' => 'test@test.com',
                'password' => '',
                'remember_token' => NULL,
                'description' => '毕业于海南师范大学',
                'video' => NULL,
                'teaching_since' => '2006-11-30 00:00:00',
                'unit_price' => 10.0,
                'enabled' => 1,
                'created_at' => '2016-09-08 05:26:43',
                'updated_at' => '2017-01-12 23:53:46',
                'deleted_at' => '2017-01-12 23:53:46',
                'avatar_file_name' => 'maxresdefault.jpg',
                'avatar_file_size' => 549898,
                'avatar_content_type' => 'image/jpeg',
                'avatar_updated_at' => '2017-01-12 23:00:26',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Test Teacher',
                'email' => 'test@test.teacher',
                'password' => '',
                'remember_token' => NULL,
                'description' => 'Test.',
                'video' => NULL,
                'teaching_since' => '2000-11-30 00:00:00',
                'unit_price' => 10.0,
                'enabled' => 0,
                'created_at' => '2017-01-12 23:54:24',
                'updated_at' => '2017-01-12 23:54:24',
                'deleted_at' => NULL,
                'avatar_file_name' => NULL,
                'avatar_file_size' => NULL,
                'avatar_content_type' => NULL,
                'avatar_updated_at' => NULL,
            ),
        ));
        
        
    }
}